config/routes.rb
PracticeBlog::Application.routes.draw do
  root to: 'welcome#index'
  resources :subjects, only: :show
  resources :articles, except: :index

  namespace :admin do
    resources :subjects
    resources :users, only: [:index, :edit, :update]
    resources :articles, except: [:index] do
      resources :sections, except: [:show, :index]
    end
  end
  
  get "sign_up", to: "users#new", as: "sign_up"
  get "sign_in", to: "sessions#new", as: "sign_in"
  get "sign_out", to: "sessions#destroy", as: "sign_out"
  resources :users, only: [:create, :edit, :update]
  resources :sessions, only: [:new, :create ]

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :subject
  belongs_to :user
	has_many :sections
  
  accepts_nested_attributes_for :sections, allow_destroy: true

  validates :title, :subject, :user, presence: true
end

app/models/permission.rb
class Permission
  
  def initialize(user)
    permit :welcome, :index
    permit :articles, :show
    permit :sessions, [:new, :create, :destroy]
    permit :subjects, :show
    permit :users, [:new, :create]
    permit :users, [:edit, :update] do |user_pro|
      user.id == user_pro.id
    end
    
    if user && user.has_role?("Author")
      permit :articles, [:new, :create]
      permit :articles, [:edit, :update, :destroy] do |article|
        article.user == user
      end
    end
    
    permit_all if user.try(:admin)
  end
  
  def permit?(controller, action, resource=nil)
    permitted = @permit_all || @permitted_actions[[controller.to_s, action.to_s]]
    permitted && (permitted == true || (resource && permitted.call(resource)))
  end
  
  def permit(controllers, actions, &block)
    @permitted_actions ||= {}
    
    Array(controllers).each do |controller|
      Array(actions).each do |action|
        @permitted_actions[[controller.to_s, action.to_s]] = block || true
      end
    end
  end
  
  def permit_all
    @permit_all = true
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  validates :name, presence: true
end

app/models/section.rb
class Section < ActiveRecord::Base
	belongs_to :article

	validates :content, :article, presence: true
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_many :articles
	validates :name, presence: true, uniqueness: { case_sensitive: false}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
  
  before_validation :generate_slug
  
  has_many :articles
  has_and_belongs_to_many :roles
  
  validates :email, :slug, presence: true, uniqueness: { message: "has been taken" }
  validates :username, presence: true
  
  def to_param
    slug
  end
  
  def has_role?(name)
    role = Role.where(name: name).take
    self.roles.include?(role)
  end
  
  private
  
  def generate_slug
    self.slug = username.parameterize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_subjects
  before_action :authorize

  delegate :permit?, to: :current_permission
  helper_method :permit?
  
  private
  helper_method :current_user
  
  def set_subjects
  	@subjects = Subject.all
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def current_resource
    nil
  end
  
  def current_permission
    @current_permission ||= Permission.new(current_user)
  end
  
  def authorize
    if !current_permission.permit?(params[:controller], params[:action], current_resource)
      redirect_to root_url
    end
  end
  
  def author?
    current_user && current_user.has_role?("Author")
  end
  
  helper_method :author?
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def show
    @article = current_resource
	end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    
    if @article.save
      flash[:notice] = "Article has been created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def edit
    @article = current_resource
  end
  
  def update
    @article = current_resource
    
    if @article.update(article_params)
      flash[:notice] = "Article has been updated"
      redirect_to @article
    else
      render 'new'
    end
  end
  
  private
    
    def article_params
      params.require(:article).permit(:title, :summary, :subject_id, :user_id, sections_attributes: [:id, :article_id, :content, :_destroy])
    end
  
  def current_resource
    @current_resource ||= Article.find(params[:id]) if params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You have signed in!"
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid username or password"
      render 'new'
    end
  end
  
  def destroy
    flash[:notice] = "You have signed out"
    session[:user_id] = nil
    redirect_to root_path
  end
  
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def show
		@subject = Subject.find(params[:id])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new user_params
    
    if @user.save
      flash[:notice] = "You have signed up"
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    
    if @user.update(user_params)
      flash[:notice] = "Profile updated!"
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  private
  def find_user
    @user = current_resource
  end
  
  def current_resource
    @current_resource ||= User.find_by_slug!(params[:id]) if params[:id]
  end
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Get Good", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
 
        <li><%= link_to "Sign up", sign_up_path %></li>
        <% if current_user %>
          <li><%= link_to "Sign out", sign_out_path %></li>
          <li><%= link_to "My Profile", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Sign in", sign_in_path %></li>
        <% end %>
        <% if author? %>
          <li><%= link_to "Write Article", new_article_path %></li>
        <% end %>
        <% if current_user.try(:admin) %>
          <li><%= link_to("Admin area", admin_subjects_path) %></li>
          <li><%= link_to("Users list", admin_users_path) %></li>
        <% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Subjects <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% @subjects.each do |subject| %>
              <li>
                <%= link_to subject.name, subject_path(subject) %>
              </li>
            <% end %>
          </ul>
        </li>       
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  
<head>
  <title>Practice Blog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
  
<body>
  
  <%= render 'layouts/navbar' %>
	
  <div class="container">
    
    <div class="row">
      <% flash.each do |name, msg| %>
        <div class="col-sm-4 alert alert-<%= name == :notice ? "success" : "danger" %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= msg %> 
        </div>
      <% end %>
    </div>

    <%= yield %>
    
  </div>

</body>
  
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>